CREATE TABLE IF NOT EXISTS country (
    id bigint PRIMARY KEY NOT NULL,
    name text NOT NULL,
    acronym text NOT NULL
);

INSERT INTO country VALUES (1, 'Togo', 'TG') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (2, 'Mauritânia', 'MR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (3, 'Israel', 'IL') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (4, 'Zimbabue', 'ZW') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (5, 'Bahamas, Ilhas', 'BS') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (6, 'Catar', 'QA') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (7, 'Ira, Republica Islâmica do', 'IR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (8, 'África do Sul', 'ZA') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (9, 'Sudão', 'SD') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (10, 'Bermudas', 'BM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (11, 'Líbia', 'LY') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (12, 'Belarus, Republica da', 'BY') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (13, 'Alemanha', 'DE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (14, 'Gana', 'GH') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (15, 'Itália', 'IT') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (16, 'Quirguiz, Republica', 'KG') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (17, 'Curaçao', 'CW') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (18, 'Svalbard e Jan Mayen', 'SJ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (19, 'Republika Srbija', 'RS') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (20, 'Arábia Saudita', 'SA') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (21, 'Gibraltar', 'GI') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (22, 'Emirados Árabes Unidos', 'AE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (23, 'Wallis e Futuna, Ilhas', 'WF') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (24, 'Eswatini', 'SZ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (25, 'Suriname', 'SR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (26, 'Eslovênia, Republica da', 'SI') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (27, 'Albânia, Republica da', 'AL') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (28, 'Feroe, Ilhas', 'FO') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (29, 'Nepal', 'NP') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (30, 'Bulgária, Republica da', 'BG') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (31, 'Micronesia', 'FM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (32, 'São Vicente e Granadinas', 'VC') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (33, 'Papua Nova Guine', 'PG') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (34, 'Mali', 'ML') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (35, 'Guine-Bissau', 'GW') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (36, 'Serra Leoa', 'SL') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (37, 'Marrocos', 'MA') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (38, 'Trinidad e Tobago', 'TT') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (39, 'Território Britânico do Oceano Indico', 'IO') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (40, 'Tunísia', 'TN') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (41, 'Dominica, Ilha', 'DM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (42, 'Austrália', 'AU') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (43, 'Jordânia', 'JO') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (44, 'Nigéria', 'NG') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (45, 'Estados Unidos', 'US') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (46, 'Madagascar', 'MG') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (47, 'Butão', 'BT') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (48, 'São Martinho, Ilha de (Parte Francesa)', 'SM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (49, 'Groenlândia', 'GL') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (50, 'Croácia (Republica da)', 'HR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (51, 'Honduras', 'HN') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (52, 'Equador', 'EC') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (53, 'Malavi', 'MW') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (54, 'Guernsey, Ilha do Canal (Inclui Alderney e Sark)', 'GG') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (55, 'Sudao do Sul', 'SS') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (56, 'Marshall, Ilhas', 'MH') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (57, 'Hong Kong', 'HK') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (58, 'Vaticano, Estado da Cidade do', 'VA') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (59, 'Kiribati', 'KI') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (60, 'Guine', 'GN') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (61, 'Colômbia', 'CO') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (62, 'Martinica', 'MQ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (63, 'Tcheca, Republica', 'CZ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (64, 'Mayotte (Ilhas Francesas)', 'YT') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (65, 'Índia', 'IN') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (66, 'Coreia, Republica Popular Democrática da', 'KP') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (67, 'Irlanda', 'IE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (68, 'Republica Dominicana', 'DO') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (69, 'Líbano', 'LB') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (70, 'Noruega', 'NO') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (71, 'Rússia, Federação da', 'RU') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (72, 'Tuvalu', 'TV') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (73, 'Países Baixos (Holanda)', 'NL') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (74, 'Virgens, Ilhas (E.U.A.)', 'VI') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (75, 'Moçambique', 'MZ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (76, 'Uruguai', 'UY') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (77, 'Polinésia Francesa', 'PF') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (78, 'Guiana francesa', 'GF') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (79, 'Áustria', 'AT') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (80, 'Malásia', 'MY') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (81, 'Gambia', 'GM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (82, 'Brasil', 'BR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (83, 'Cook, Ilhas', 'CK') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (84, 'Malta', 'MT') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (85, 'Tanzânia, Republica Unida da', 'TZ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (86, 'Norfolk, Ilha', 'NF') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (87, 'Congo', 'CG') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (88, 'Nicarágua', 'NI') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (89, 'Panamá', 'PA') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (90, 'Peru', 'PE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (91, 'Palau', 'PW') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (92, 'Camarões', 'CM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (93, 'Espanha', 'ES') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (94, 'Porto Rico', 'PR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (95, 'Turquia', 'TR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (96, 'Indonésia', 'ID') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (97, 'Man, Ilha de', 'IM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (98, 'Laos, Republica Popular Democrática do', 'LA') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (99, 'Niue, Ilha', 'NU') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (100, 'Eslovaca, Republica', 'SK') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (101, 'Bouvet, Ilha', 'BV') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (102, 'Salomão, Ilhas', 'SB') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (103, 'Bósnia-herzegovina (Republica da)', 'BA') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (104, 'Suíça', 'CH') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (105, 'Bangladesh', 'BD') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (106, 'Mianmar (Birmânia)', 'MM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (107, 'Chile', 'CL') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (108, 'Barbados', 'BB') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (109, 'Síria, Republica Árabe da', 'SY') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (110, 'Liechtenstein', 'LI') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (111, 'Iraque', 'IQ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (112, 'Jamaica', 'JM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (113, 'Uzbequistão, Republica do', 'UZ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (114, 'Burkina Faso', 'BF') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (115, 'Bolívia', 'BO') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (116, 'Virgens, Ilhas (Britânicas)', 'VG') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (117, 'Ucrânia', 'UA') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (118, 'São Cristovão e Neves, Ilhas', 'KN') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (119, 'Níger', 'NE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (120, 'Etiópia', 'ET') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (121, 'Coreia, Republica da', 'KR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (122, 'Nauru', 'NR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (123, 'Costa do Marfim', 'CI') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (124, 'El Salvador', 'SV') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (125, 'Filipinas', 'PH') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (126, 'Senegal', 'SN') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (127, 'Venezuela', 'VE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (128, 'Bonaire', 'AN') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (129, 'Costa Rica', 'CR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (130, 'Egito', 'EG') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (131, 'Belize', 'BZ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (132, 'Gabão', 'GA') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (133, 'Bélgica', 'BE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (134, 'Islândia', 'IS') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (135, 'Djibuti', 'DJ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (136, 'Guine-Equatorial', 'GQ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (137, 'Aruba', 'AW') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (138, 'Montenegro', 'ME') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (139, 'Timor Leste', 'TL') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (140, 'Bahrein, Ilhas', 'BH') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (141, 'Antigua e Barbuda', 'AG') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (142, 'Angola', 'AO') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (143, 'Sri Lanka', 'LK') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (144, 'São Tome e Príncipe, Ilhas', 'ST') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (145, 'Zâmbia', 'ZM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (146, 'Tadjiquistao, Republica do', 'TJ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (147, 'Lituânia, Republica da', 'LT') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (148, 'Brunei', 'BN') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (149, 'Dinamarca', 'DK') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (150, 'Vietnã', 'VN') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (151, 'Iémen', 'YE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (152, 'Letônia, Republica da', 'LV') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (153, 'Polônia, Republica da', 'PL') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (154, 'Tonga', 'TO') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (155, 'Pitcairn, Ilha', 'PN') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (156, 'San Marino', 'SM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (157, 'Macau', 'MO') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (158, 'Chipre', 'CY') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (159, 'Guadalupe', 'GP') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (160, 'Republica Centro-Africana', 'CF') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (161, 'Estônia, Republica da', 'EE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (162, 'Luxemburgo', 'LU') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (163, 'Seychelles', 'SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (164, 'Canadá', 'CA') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (165, 'Romênia', 'RO') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (166, 'Comores, Ilhas', 'KM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (167, 'Andorra', 'AD') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (168, 'Turcomenistão, Republica do', 'TM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (169, 'Georgia, Republica da', 'GE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (170, 'Botsuana', 'BW') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (171, 'Samoa', 'WS') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (172, 'Jersey, Ilha do Canal', 'JE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (173, 'Armênia, Republica da', 'AM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (174, 'São Martinho, Ilha de (Parte Holandesa)', 'SM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (175, 'Ruanda', 'RW') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (176, 'Ilha Heard e Ilhas McDonald', 'HM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (177, 'Formosa (Taiwan)', 'TW') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (178, 'Eritreia', 'ER') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (179, 'Argélia', 'DZ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (180, 'Granada', 'GD') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (181, 'Samoa Americana', 'AS') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (182, 'México', 'MX') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (183, 'Afeganistão', 'AF') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (184, 'Mauricio', 'MU') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (185, 'Ilhas Caimã', 'KY') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (186, 'Antartica', 'AQ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (187, 'Suécia', 'SE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (188, 'Toquelau, Ilhas', 'TK') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (189, 'Libéria', 'LR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (190, 'Nova Caledonia', 'NC') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (191, 'Argentina', 'AR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (192, 'Santa Helena', 'SH') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (193, 'Kuwait', 'KW') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (194, 'Finlândia', 'FI') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (195, 'Ilha Herad e Ilhas Macdonald', 'AU') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (196, 'Ilhas Menores Distantes dos Estados Unidos', 'UM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (197, 'Namíbia', 'NA') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (198, 'Somalia', 'SO') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (199, 'Oma', 'OM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (200, 'Guam', 'GU') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (201, 'Azerbaijão, Republica do', 'AZ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (202, 'Tailândia', 'TH') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (203, 'Benin', 'BJ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (204, 'Cazaquistão, Republica do', 'KZ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (205, 'Turcas e Caicos, Ilhas', 'TC') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (206, 'China, Republica Popular', 'CN') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (207, 'Coletividade de São Bartolomeu', 'BL') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (208, 'Saara Ocidental', 'EH') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (209, 'Cingapura', 'SG') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (210, 'São Bartolomeu', 'FR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (211, 'Maldivas', 'MV') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (212, 'Haiti', 'HT') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (213, 'Mongólia', 'MN') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (214, 'Moldávia, Republica da', 'MD') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (215, 'Uganda', 'UG') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (216, 'Hungria, Republica da', 'HU') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (217, 'Terras Austrais e Antárcticas Francesas', 'TF') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (218, 'Marianas do Norte', 'MP') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (219, 'Iugoslávia, República Fed. da', 'YU') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (220, 'Lesoto', 'LS') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (221, 'Palestina', 'PS') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (222, 'Chade', 'TD') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (223, 'Reino Unido', 'GB') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (224, 'São Pedro e Miquelon', 'PM') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (225, 'Guatemala', 'GT') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (226, 'Cocos (Keeling), Ilhas', 'CC') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (227, 'Anguila', 'AI') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (228, 'Falkland (Ilhas Malvinas)', 'FK') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (229, 'Japão', 'JP') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (230, 'Quênia', 'KE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (231, 'Portugal', 'PT') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (232, 'Burundi', 'BI') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (233, 'Ilhas Geórgia do Sul e Sandwich do Sul', 'GS') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (234, 'Antártida', 'AQ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (235, 'Macedônia do Norte', 'MK') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (236, 'Fiji', 'FJ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (237, 'Guiana', 'GY') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (238, 'Vanuatu', 'VU') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (239, 'Camboja', 'KH') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (240, 'Cabo Verde, Republica de', 'CV') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (241, 'Congo, Republica Democrática do', 'CD') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (242, 'Reunião, Ilha', 'RE') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (243, 'Montserrat, Ilhas', 'MS') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (244, 'Franca', 'FR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (245, 'Cuba', 'CU') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (246, 'Mônaco', 'MC') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (247, 'Paraguai', 'PY') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (248, 'Terras Austrais e Antárticas Francesas', 'TF') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (249, 'Grécia', 'GR') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (250, 'Nova Zelândia', 'NZ') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (251, 'Santa Lucia', 'LC') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (252, 'Christmas, Ilha (Navidad)', 'CX') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (253, 'Aland, Ilhas', 'AX') ON CONFLICT (id) DO NOTHING;
INSERT INTO country VALUES (254, 'Paquistão', 'PK') ON CONFLICT (id) DO NOTHING;

